{% set name = "pregex" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pregex-{{ version }}.tar.gz
  sha256: ea9bfbf75b986a4b1e09a8fa78cf83607fa7a066bd6cddb4be962b5aff3726dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - pregex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manoss96/pregex
  doc_url: https://pregex.readthedocs.io/
  summary: Programmable Regular Expressions
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
