{% set name = "pregex" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pregex-{{ version }}.tar.gz
  sha256: 3a8f103a63e7a02a993b9e45932df724b9e1acc96f513e33c3036e1525cd820a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - pregex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manoss96/pregex
  doc_url: https://pregex.readthedocs.io/
  summary: Programmable Regular Expressions
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
